"use client";
import { useEffect, useRef, useState } from 'react';
import { Radar } from 'lucide-react';
import type { RadarDiscovery, RadarResponse } from '@/lib/radar/types';
import { LABELS, defaults, isNewGem, researchIdentity, safeUrl, selectDiscoveries, statusOf } from '@/lib/radar/view.mjs';
const readable = (value: string | null | undefined) => value && Number.isFinite(Date.parse(value)) ? new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}) : 'Not available';
function External({url,children}:{url:string;children:React.ReactNode}) {const safe=safeUrl(url);return safe?<a href={safe} target="_blank" rel="noopener noreferrer">{children}</a>:<span>{children}</span>;}
export function CaptainsRadar({onResearch}:{onResearch:(identity:string)=>void}) {
 const [data,setData]=useState<RadarResponse|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[warning,setWarning]=useState('');
 const [filters,setFilters]=useState(defaults),[search,setSearch]=useState(''),[sort,setSort]=useState('newest'),[limit,setLimit]=useState(12),[open,setOpen]=useState<string[]>([]),[busy,setBusy]=useState<string[]>([]),[errors,setErrors]=useState<Record<string,string>>({});
 const locks=useRef(new Set<string>());
 useEffect(()=>{let active=true;fetch('/api/radar',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{if(active)setData(d);}).catch(()=>{if(active)setWarning('Radar cache could not be loaded. Try Refresh Radar.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 async function refresh(){if(locks.current.has('refresh'))return;locks.current.add('refresh');setRefreshing(true);setWarning('');try{const r=await fetch('/api/radar/refresh',{method:'POST'});if(!r.ok)throw Error();setData(await r.json());}catch{setWarning('Radar refresh unavailable. Existing discoveries remain available.');}finally{locks.current.delete('refresh');setRefreshing(false);}}
 async function classify(d:RadarDiscovery){if(locks.current.has(d.id))return;locks.current.add(d.id);setBusy(v=>[...v,d.id]);setErrors(v=>({...v,[d.id]:''}));try{const r=await fetch('/api/radar/classify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:[d.id],refresh:statusOf(d)!=='UNCLASSIFIED'})});if(!r.ok)throw Error();const result=(await r.json()).results?.find((v:{id:string})=>v.id===d.id);if(!result||result.status==='FAILED')throw Error();setData(v=>v?{...v,discoveries:v.discoveries.map(item=>item.id===d.id?{...item,classification:result.classification,classificationStatus:result.classification.status,classificationEvidence:result.classificationEvidence,classificationCache:result.classificationCache}:item)}:v);}catch{setErrors(v=>({...v,[d.id]:'Classification evidence unavailable. Please try again.'}));}finally{locks.current.delete(d.id);setBusy(v=>v.filter(id=>id!==d.id));}}
 const records=data?.discoveries||[],visible:RadarDiscovery[]=selectDiscoveries(records,filters,search,sort);
 const reset=()=>{setFilters(defaults());setSearch('');setSort('newest');setLimit(12);};
 const networks=Array.from(new Set(records.flatMap(d=>d.classification?.networks||[]))).sort();
 return <section className="brand-card captain-radar" aria-labelledby="radar-heading">
  <div className="radar-top"><div className="scan-heading"><span className="section-icon"><Radar aria-hidden="true"/></span><div><p className="eyebrow">FRESH SIGNALS</p><h2 id="radar-heading">Captain’s Radar</h2></div></div><button className="radar-primary" disabled={refreshing} onClick={refresh}>{refreshing?'Refreshing Radar…':'Refresh Radar'}</button></div>
  <p>Fresh crypto signals discovered from trusted scouting sources.</p>
  <p className="radar-muted">Radar refreshed: <time dateTime={data?.refreshedAt||undefined}>{readable(data?.refreshedAt)}</time> · Cached discoveries. Research and classification require your action.</p>
  <div role="status" aria-live="polite">{loading&&<p>Loading cached Radar…</p>}{warning&&<p className="radar-warning">{warning}</p>}{!!data?.issues.length&&<p className="radar-warning">Some Radar sources could not be refreshed. Existing discoveries remain available.</p>}</div>
  <div className="radar-health">{Object.entries(data?.sources||{}).map(([id,s])=><span key={id}>{/website/i.test(id)?'FrontRun Website':/x/i.test(id)?'FrontRun X':id}: {({AVAILABLE:'Available',PARTIAL:'Partial',UNAVAILABLE:'Unavailable',NOT_CONFIGURED:'Not configured'} as Record<string,string>)[s.status]||'Unknown'}</span>)}</div>
  <div className="radar-summary">{[['Total discoveries',records.length],['Crypto Relevant',records.filter(d=>statusOf(d)==='CRYPTO_RELEVANT').length],['Possibly Crypto',records.filter(d=>statusOf(d)==='POSSIBLY_CRYPTO').length],['Needs Review',records.filter(d=>d.classification?.needsReview).length]].map(([label,count])=><div key={label}><strong>{count}</strong><span>{label}</span></div>)}</div>
  {!!records.length&&<><label className="radar-search">Search Radar<input value={search} onChange={e=>{setSearch(e.target.value);setLimit(12);}} placeholder="Project, handle, category, network or reason"/></label>
  <details className="radar-filters" open><summary>Filters and sorting</summary><fieldset><legend>Classification</legend>{Object.entries(LABELS).map(([value,label])=><label key={value}><input type="checkbox" checked={filters.statuses.includes(value)} onChange={()=>{setFilters(f=>({...f,statuses:f.statuses.includes(value)?f.statuses.filter(s=>s!==value):[...f.statuses,value]}));setLimit(12);}}/>{label}</label>)}</fieldset>
  <div className="radar-filter-row"><label>Network<select aria-label="Network" value={filters.network} onChange={e=>setFilters(f=>({...f,network:e.target.value}))}><option value="">All networks</option>{networks.map(n=><option key={n}>{n}</option>)}</select></label><label>Source<select aria-label="Source" value={filters.source} onChange={e=>setFilters(f=>({...f,source:e.target.value}))}><option value="">All sources</option><option>FrontRun Website</option><option>FrontRun X</option></select></label><label>Sort by<select aria-label="Sort by" value={sort} onChange={e=>setSort(e.target.value)}>{[['newest','Newest discovered'],['flag','Earliest FrontRun flag'],['confidence','Highest confidence'],['lead','Longest FrontRun lead time'],['funding','Funding mentioned']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div>
  <div className="radar-filter-row">{[['review','Needs Review'],['funding','Funding mention'],['recent','Discovered in last 30 days']].map(([key,label])=><label key={key}><input type="checkbox" checked={filters[key as 'review'|'funding'|'recent']} onChange={e=>setFilters(f=>({...f,[key]:e.target.checked}))}/>{label}</label>)}<button onClick={reset}>Reset filters</button></div></details></>}
  {records.length>0&&records.every(d=>statusOf(d)==='UNCLASSIFIED')&&<p className="radar-warning">Radar has discoveries waiting for crypto relevance classification. Unclassified discoveries are shown until classification is available.</p>}
  {!loading&&!records.length&&<div className="radar-empty">No Radar discoveries loaded yet. Use Refresh Radar to scout trusted sources.</div>}
  {!!records.length&&!visible.length&&<div className="radar-empty">No discoveries match these filters. <button onClick={reset}>Reset filters</button></div>}
  <p className="radar-muted" role="status">{records.length>0?`${visible.length} matching discoveries`:''}</p>
  <div className="radar-grid">{visible.slice(0,limit).map(d=>{const c=d.classification,expanded=open.includes(d.id),identity=researchIdentity(d);return <article className="radar-card" key={d.id}>
   <div className="radar-badges"><span className={`radar-badge radar-${statusOf(d).toLowerCase()}`}>{LABELS[statusOf(d) as keyof typeof LABELS]}</span>{c?.confidence!=null&&<span>{c.confidence}% confidence</span>}{isNewGem(d)&&<span className="radar-badge">◇ New Gem</span>}{c?.needsReview&&<span className="radar-badge" title="CaptainScout found incomplete, conflicting, or weak evidence.">Needs Review</span>}</div>
   <h3>{d.projectName}</h3>{d.projectHandle&&<p className="radar-handle">@{d.projectHandle.replace(/^@/,'')}</p>}
   {d.rawCategory&&<p className="radar-muted">FrontRun category: {d.rawCategory}</p>}
   <div className="radar-badges">{c?.networks.map(n=><span className="radar-badge" key={n}>{n}</span>)}</div>
   {d.fundingMention&&<p>FrontRun funding mention: <strong>{d.fundingMention}</strong></p>}
   {d.frontRunFlaggedAt&&<p>FrontRun flagged: <time dateTime={d.frontRunFlaggedAt}>{readable(d.frontRunFlaggedAt)}</time></p>}
   {d.frontRunLeadTimeDays!=null&&<p>Lead-time claim: {d.frontRunLeadTimeDays} days early</p>}
   <p>{c?.reason||'Crypto relevance has not been classified yet.'}</p>
   <p className="radar-muted">Discovered via {d.source} · {d.evidence.length+(d.classificationEvidence?.length||0)} evidence items</p>
   <p className="radar-muted">First retrieved: <time dateTime={d.discoveredAt}>{readable(d.discoveredAt)}</time></p>
   {c?.classifiedAt&&<p className="radar-muted">Classification checked: <time dateTime={c.classifiedAt}>{readable(c.classifiedAt)}</time>{d.classificationCache?.status==='STALE'?' · Stale':''}</p>}
   <div className="radar-actions"><button className="radar-primary" disabled={!identity} title={!identity?'No reliable project identifier available':undefined} onClick={()=>identity&&onResearch(identity)}>Research Project</button><button disabled={busy.includes(d.id)} onClick={()=>classify(d)}>{busy.includes(d.id)?'Checking relevance…':statusOf(d)==='UNCLASSIFIED'?'Classify':'Refresh Classification'}</button><button aria-expanded={expanded} aria-controls={`radar-details-${d.id}`} onClick={()=>setOpen(v=>expanded?v.filter(id=>id!==d.id):[...v,d.id])}>{expanded?'Hide details':'Evidence & details'}</button></div>
   {!identity&&<p className="radar-muted">No reliable project identifier available</p>}{errors[d.id]&&<p role="alert" className="radar-warning">{errors[d.id]}</p>}
   {expanded&&<div id={`radar-details-${d.id}`} className="radar-details"><h4>Crypto signals</h4><p>{c?.cryptoSignals.join(' · ')||'No classified signals available'}</p>{c&&<p>Token evidence: {c.tokenStatus.replaceAll('_',' ')} · Review: {c.needsReview?'Needs Review':'Not flagged'}</p>}<h4>Raw FrontRun discovery</h4><p>{d.rawDescription}</p>{d.projectWebsite&&<p><External url={d.projectWebsite}>Project website</External></p>}{d.founderNames.length>0&&<p>Founders: {d.founderNames.join(', ')}</p>}{d.investors.length>0&&<p>FrontRun investor mentions: {d.investors.join(', ')}</p>}<h4>Provenance & source events</h4>{d.evidence.map((e,i)=><div key={`${e.eventId}-${i}`}><External url={e.sourceUrl}>{e.sourceTitle||e.source} · {e.sourceType}</External><p>{e.text}</p><p className="radar-muted">{e.verification} · First retrieved: {readable(e.checkedAt)}{e.sourcePublishedAt?` · Published: ${readable(e.sourcePublishedAt)}`:''}</p>{e.originatingPostUrl&&<External url={e.originatingPostUrl}>Originating post</External>}</div>)}<h4>Classification evidence</h4>{d.classificationEvidence?.map(e=><div key={e.id}><External url={e.sourceUrl}>{e.title||e.sourceType}</External><p>{e.snippet}</p><p className="radar-muted">{e.verification} · {e.signalStrength} · Checked {readable(e.checkedAt)}{e.stale?' · Stale':''}</p></div>)}</div>}
  </article>;})}</div>
  {visible.length>limit&&<button className="radar-more" onClick={()=>setLimit(v=>v+12)}>Show more ({visible.length-limit} remaining)</button>}
 </section>;
}
