import test from 'node:test';
import assert from 'node:assert/strict';
import {classifyEvidence, createClassificationService, collectClassificationEvidence} from '../lib/radar/classification.mjs';
const now=new Date('2026-10-04T12:00:00Z');
const source=(snippet,type='OFFICIAL',extra={})=>({sourceType:type,sourceUrl:type==='OFFICIAL'?'https://project.example/':'https://frontrun.vc/receipt',title:'Product',snippet,provider:'fixture',verification:'VERIFIED',checkedAt:now.toISOString(),...extra});
const classify=(text,extra={})=>classifyEvidence([source(text)],{now,...extra}).classification;
const ordinary='Our robotics platform builds industrial robot arms for assembly lines and factories. We provide simulation tools, mechanical design and scheduling software for manufacturing customers worldwide.';
const discovery={id:'one',identityKeys:['x:project'],projectHandle:'project',projectWebsite:'https://project.example/',rawCategory:'Robotics',evidence:[{sourceUrl:'https://frontrun.vc/receipt',sourceTitle:'Discovery',text:'Industrial robotics product',verification:'FETCH_VERIFIED',checkedAt:now.toISOString()}]};
for(const [name,text,network] of [
  ['Robotics','Our robots use Base for trajectory proofs.','Base'],
  ['FinTech','Our product provides stablecoin settlement for businesses.',null],
  ['AI','We use ZK proofs for verification of compute results.',null],
  ['testnet wallet','Our testnet offers wallet connect for product use.',null],
  ['tokenless','Our product uses blockchain as product infrastructure.',null],
])test(name+' strong product evidence',()=>{const c=classify(text);assert.equal(c.status,'CRYPTO_RELEVANT');assert.ok(c.confidence>=70);assert.deepEqual(c.networks,network?[network]:[]);assert.ok(c.evidenceIds.length);});
test('medium roadmap and token planned remain possible',()=>{for(const text of ['Our roadmap plans blockchain integration.','Token coming soon.','Our testnet is available.']){const c=classify(text);assert.equal(c.status,'POSSIBLY_CRYPTO');assert.ok(c.confidence>=35&&c.confidence<70);assert.equal(c.needsReview,true);}assert.equal(classify('Token coming soon.').tokenStatus,'PLANNED');});
test('independent medium sources qualify; duplicate source does not',()=>{const a=source('Our roadmap plans blockchain integration.');const b=source('Our testnet is available.','FRONTRUN');assert.equal(classifyEvidence([a,b],{now}).classification.status,'CRYPTO_RELEVANT');assert.equal(classifyEvidence([a,a],{now}).classification.status,'POSSIBLY_CRYPTO');});
for(const text of ['Funded by Paradigm, a crypto investor.','Founder previously worked at Coinbase on smart contracts.','Investor uses Ethereum.','Our partner is a blockchain company.','We attended a crypto conference.','Company follows crypto accounts.','NFTs in a marketing campaign.','We accept crypto payments for merchandise only.'])test('reject standalone context: '+text,()=>{const c=classifyEvidence([source(ordinary+' '+text),source('Industrial robotics','FRONTRUN')],{now}).classification;assert.equal(c.status,'NON_CRYPTO');assert.deepEqual(c.networks,[]);});
test('weak marketing cannot produce crypto relevant',()=>{for(const text of ['Generic AI + Web3 community.','Decentralized AI is the future.','Job post requires blockchain skills.'])assert.equal(classify(text).status,'POSSIBLY_CRYPTO');});
test('absence needs official substantive plus FrontRun coverage',()=>{assert.equal(classify(ordinary).status,'UNCLASSIFIED');const c=classifyEvidence([source(ordinary),source('Robotics','FRONTRUN')],{now}).classification;assert.equal(c.status,'NON_CRYPTO');assert.ok(c.confidence<35);assert.equal(classify('Short page').status,'UNCLASSIFIED');});
test('stale and unverified strong claims cannot qualify',()=>{for(const extra of [{checkedAt:'2026-01-01'},{verification:'UNVERIFIED'}]){const c=classifyEvidence([source('Product uses Ethereum for onchain records.','OFFICIAL',extra)],{now}).classification;assert.equal(c.status,'POSSIBLY_CRYPTO');assert.equal(c.needsReview,true);assert.deepEqual(c.networks,[]);}});
test('ambiguous identity retained unclassified',()=>{assert.equal(classify('Our product uses blockchain.',{identitySafe:false}).status,'UNCLASSIFIED');});
test('negative evidence creates review flag for conflicting product claims',()=>{assert.equal(classify('Product uses blockchain. We do not use crypto.').needsReview,true);assert.equal(classify('We do not use blockchain.').status,'UNCLASSIFIED');});
test('network extraction requires product signal and explicit chain; ordinary base is not Base',()=>{assert.deepEqual(classify('Our product uses blockchain in its customer base.').networks,[]);assert.deepEqual(classify('Product deployed on Solana.').networks,['Solana']);});
test('token status extraction and no token requirement',()=>{assert.equal(classify('Our governance token is live.').tokenStatus,'LIVE');assert.equal(classify('Our token announced for the protocol.').tokenStatus,'ANNOUNCED');assert.equal(classify('Product uses blockchain.').tokenStatus,'NO_TOKEN_EVIDENCE');});
test('cache, refresh, expiry, evidence changes and clone isolation',async()=>{let clock=now,calls=0;const service=createClassificationService({now:()=>clock,collect:async()=>{calls++;return [source('Product uses blockchain.')];}});let r=await service.batch([discovery]);r.results[0].classification.networks.push('fake');assert.deepEqual(service.peek(discovery).classification.networks,[]);assert.equal((await service.batch([discovery])).results[0].status,'CACHED');assert.equal(calls,1);await service.batch([discovery],{refresh:true});assert.equal(calls,2);clock=new Date(now.getTime()+3600001);assert.equal(service.peek(discovery).classificationCache.status,'STALE');await service.batch([discovery]);assert.equal(calls,3);assert.equal(service.peek({...discovery,evidence:[]}).classificationCache.status,'STALE');});
test('failure isolation preserves earlier success; bounded batches and concurrency',async()=>{let fail=false,release;const service=createClassificationService({now:()=>now,collect:async d=>{if(d.id==='bad'||fail)throw Error('secret');return [source('Product uses blockchain.')];}});let r=await service.batch([discovery,{...discovery,id:'bad',identityKeys:['x:bad']}]);assert.deepEqual(r.results.map(r=>r.status),['CLASSIFIED','FAILED']);fail=true;r=await service.batch([discovery],{refresh:true});assert.equal(r.results[0].status,'FAILED');assert.equal(r.results[0].classification.status,'CRYPTO_RELEVANT');assert.ok(!JSON.stringify(r).includes('secret'));await assert.rejects(service.batch(Array(6).fill(discovery)));const busy=createClassificationService({collect:()=>new Promise(resolve=>release=resolve)});const pending=busy.batch([discovery]);await assert.rejects(busy.batch([discovery]));release([]);await pending;});
test('raw category never controls decision',async()=>{const service=createClassificationService({now:()=>now,collect:async d=>[source(d.rawCategory==='Robotics'?'Our robots use Base for trajectory proofs.':ordinary),source('Discovery','FRONTRUN')]});assert.equal((await service.batch([discovery])).results[0].classification.status,'CRYPTO_RELEVANT');assert.equal((await service.batch([{...discovery,rawCategory:'Blockchain'}],{refresh:true})).results[0].classification.status,'NON_CRYPTO');});
test('fetch failure cannot imply non crypto; no name-only search',async()=>{let queries=0;const options={now,fetchPage:async()=>{throw Error('secret');},provider:{search:async()=>{queries++;return [];}}};const sources=await collectClassificationEvidence(discovery,options);assert.equal(classifyEvidence(sources,{now}).classification.status,'UNCLASSIFIED');const before=queries;await collectClassificationEvidence({...discovery,projectWebsite:null,projectHandle:null},options);assert.equal(queries,before);});
test('official fetch bounded and redirects cannot change identity',async()=>{let calls=0;const sources=await collectClassificationEvidence(discovery,{now,fetchPage:async()=>{calls++;return {url:'https://wrong.example/',html:'<p>Product uses Ethereum.</p>'};}});assert.equal(calls,1);assert.ok(!sources.some(s=>s.sourceType==='OFFICIAL'));});
test('exact owned X snippets remain unverified and do not infer websites',async()=>{const sources=await collectClassificationEvidence({...discovery,projectWebsite:null},{now,provider:{search:async()=>[{url:'https://x.com/project/status/1',title:'Project',snippet:'Product uses Ethereum.'},{url:'https://x.com/project_other/status/1',title:'Other',snippet:'Product uses Solana.'}]}});const c=classifyEvidence(sources,{now}).classification;assert.equal(c.status,'POSSIBLY_CRYPTO');assert.deepEqual(c.networks,[]);assert.equal(sources.length,2);});
test('future technical claims do not become strong',()=>{assert.equal(classify('Our roadmap will use smart contracts and deploy on Ethereum.').status,'POSSIBLY_CRYPTO');});
test('API validates origin, batch limits, unknown identities, refresh and sanitizes errors',async()=>{
  const {readFileSync}=await import('node:fs');const {createRequire}=await import('node:module');const ts=createRequire(import.meta.url)('typescript');
  let calls=0,fail=false;globalThis.__classificationApi={radar:{get:()=>({discoveries:[discovery]})},classifier:{batch:async(ds,options)=>{calls++;assert.equal(ds[0].id,'one');assert.equal(options.refresh,true);if(fail)throw Error('secret');return {results:[]};}}};
  let code=readFileSync(new URL('../app/api/radar/classify/route.ts',import.meta.url),'utf8').replace(/import \{ NextResponse \} from "next\/server";/,'const NextResponse=Response;').replace(/import \{ radarService \} from "@\/lib\/radar\/discovery.mjs";/,'const radarService=globalThis.__classificationApi.radar;').replace(/import \{ classificationService \} from "@\/lib\/radar\/classification.mjs";/,'const classificationService=globalThis.__classificationApi.classifier;');
  code=ts.transpileModule(code,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2020}}).outputText;
  const {POST}=await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);
  const request=(body,origin)=>new Request('https://captain.example/api/radar/classify',{method:'POST',body:JSON.stringify(body),headers:origin?{origin}:{}});
  assert.equal((await POST(request({ids:['one']},'https://evil.example'))).status,403);
  for(const body of [{ids:[]},{ids:Array(6).fill('one')},{ids:['one','one']},{ids:['one'],refresh:'yes'},null])assert.equal((await POST(request(body))).status,400);
  assert.equal((await POST(request({ids:['unknown']}))).status,404);assert.equal(calls,0);
  assert.equal((await POST(request({ids:['one'],refresh:true}))).status,200);fail=true;const failed=await POST(request({ids:['one'],refresh:true}));assert.equal(failed.status,503);assert.ok(!(await failed.text()).includes('secret'));delete globalThis.__classificationApi;
});
test('explicit unique project flag in retained evidence anchors identity; conflicting handles do not',async()=>{
  const {resolveClassificationIdentity}=await import('../lib/radar/classification.mjs');
  const d={...discovery,projectWebsite:null,projectHandle:null,evidence:[{...discovery.evidence[0],text:'FUNDRAISE: @frontrunvc flagged @hifiHQ. HIFI builds infrastructure for tokenized capital markets.'}]};
  assert.equal(resolveClassificationIdentity(d).handle,'hifihq');
  const service=createClassificationService({now:()=>now,collect:async()=>[source(d.evidence[0].text,'FRONTRUN')]});assert.equal((await service.batch([d])).results[0].classification.status,'CRYPTO_RELEVANT');
  assert.equal(resolveClassificationIdentity({...d,evidence:[...d.evidence,{...d.evidence[0],text:'frontrunvc flagged @other'}]}).handle,null);
});
test('evidence references are unique and point to retained evidence',()=>{const r=classifyEvidence([source('Product uses blockchain. Product uses blockchain.')],{now});assert.equal(r.evidence.length,1);assert.deepEqual(r.classification.evidenceIds,r.evidence.map(e=>e.id));});
test('ordinary base usage is not blockchain infrastructure',()=>{assert.equal(classify('Our platform is built on a knowledge base.').status,'UNCLASSIFIED');});
test('unavailable refresh retains earlier classification and exposes staleness',async()=>{let fail=false;const service=createClassificationService({now:()=>now,collect:async()=>fail?[]:[source('Product uses blockchain.')]});await service.batch([discovery]);fail=true;const result=(await service.batch([discovery],{refresh:true})).results[0];assert.equal(result.status,'FAILED');assert.equal(result.classification.status,'CRYPTO_RELEVANT');assert.equal(result.classificationCache.status,'STALE');assert.equal(result.classification.needsReview,true);});
