import test from 'node:test';
import assert from 'node:assert/strict';
import {parseDiscoveryText,normalizeDiscoveries,normalizeHandle,canonicalUrl,ownsFrontRunPost,normalizeDate,FrontRunWebsiteSource,FrontRunXSource,createRadarService,RADAR_LIMITS} from '../lib/radar/discovery.mjs';
const provenance={source:'FrontRun Website',sourceType:'WEBSITE',sourceUrl:'https://frontrun.vc/blog/receipt',sourcePublishedAt:'2026-09-15',checkedAt:'2026-10-04T12:00:00Z',verification:'FETCH_VERIFIED'};
const parse=text=>parseDiscoveryText(text,provenance);
const fixtures={early:'EARLY: @Project - 6 followers (Robotics) founder: @Alice flagged Aug 10, 2026 website https://project.example/?utm_source=x',multi:'EARLY: @Alpha - 12 followers (AI)\nEARLY: @Beta - 2 followers (Healthcare)',funding:'Project raised $41M seed led by Accel and a16z',editorial:'Ethereum is popular. Acme builds good software.',stealth:'EARLY: Stealth - founder @Alice',malformed:'EARLY: @ -- followers'};
test('EARLY fields, explicit founders, dates, websites and provenance',()=>{const [d]=parse(fixtures.early);assert.equal(d.projectHandle,'project');assert.equal(d.followerCount,6);assert.equal(d.rawCategory,'Robotics');assert.deepEqual(d.founderHandles,['alice']);assert.equal(d.frontRunFlaggedAt,'2026-08-10');assert.equal(d.projectWebsite,'https://project.example/');assert.equal(d.evidence[0].sourcePublishedAt,'2026-09-15');assert.equal(d.classificationStatus,'UNCLASSIFIED');});
test('multiple entries retain all categories',()=>assert.equal(parse(fixtures.multi).length,2));
test('funding remains source-attributed raw information',()=>{const [d]=parse(fixtures.funding);assert.equal(d.fundingAmount,'$41M');assert.equal(d.fundingRound,'seed');assert.deepEqual(d.investors,['Accel','a16z']);assert.ok(d.evidence[0].text.includes('$41M'));});
test('editorial, unknown stealth identity and malformed entry rejected',()=>{for(const key of ['editorial','stealth','malformed'])assert.deepEqual(parse(fixtures[key]),[]);});
test('handles and URLs canonicalized conservatively',()=>{assert.equal(normalizeHandle('@PrOjEcT'),'project');assert.equal(normalizeHandle('bad/handle'),null);assert.equal(canonicalUrl('https://www.twitter.com/Project/?utm_source=x'),'https://x.com/project');assert.equal(canonicalUrl('https://WWW.Example.com/path/?utm_source=x'),'https://example.com/path');assert.throws(()=>canonicalUrl('https://user:pass@example.com'));});
test('X exact source ownership',()=>{for(const url of ['https://x.com/frontrunvc/status/123','https://twitter.com/FrontRunVC/status/123'])assert.ok(ownsFrontRunPost(url));for(const url of ['https://x.com/other/status/123','https://x.com/frontrunvc','https://x.com/frontrunvc.evil/status/123','http://x.com/frontrunvc/status/123'])assert.equal(ownsFrontRunPost(url),false);});
test('dates never invent precision from vague dates',()=>{assert.equal(normalizeDate('months ago'),null);assert.equal(normalizeDate('2026-09-15'),'2026-09-15');assert.equal(normalizeDate('2026-02-30'),null);});
test('same project merges across X and website, retains events and first flag',()=>{const a=parse('EARLY: @Project - 6 followers flagged 2026-08-10')[0];const b=parseDiscoveryText('EARLY: @PROJECT - 20 followers flagged 2026-08-20 https://project.example/',{...provenance,source:'FrontRun X',sourceUrl:'https://x.com/frontrunvc/status/123'})[0];const d=normalizeDiscoveries([b,a])[0];assert.equal(normalizeDiscoveries([a,b]).length,1);assert.equal(d.frontRunFlaggedAt,'2026-08-10');assert.equal(d.evidence.length,2);assert.equal(d.projectWebsite,'https://project.example/');assert.equal(d.id,normalizeDiscoveries([a,b])[0].id);});
test('similar names with different handles do not overmerge',()=>{assert.equal(normalizeDiscoveries(parse('EARLY: @One - 6 followers\nEARLY: @Two - 6 followers')).length,2);});
test('article parses links and originating post without inventing URLs',async()=>{const adapter=new FrontRunWebsiteSource(async url=>({url,html:'<title>Receipt</title><p>EARLY: @Project - 6 followers (AI) <a href="https://project.example/">project website</a> <a href="https://x.com/frontrunvc/status/123">original post</a></p>'}));const result=await adapter.discover({checkedAt:provenance.checkedAt,deadline:Date.now()+1000});assert.equal(result.events[0].projectWebsite,'https://project.example/');assert.equal(result.events[0].evidence[0].originatingPostUrl,'https://x.com/frontrunvc/status/123');});
test('bounded website crawl and no external fetch',async()=>{const requested=[];const adapter=new FrontRunWebsiteSource(async url=>{requested.push(url);return {url,html:'<p>EARLY: @Project - 6 followers</p>'+Array.from({length:40},(_,i)=>`<a href="/blog/${i}">EARLY receipt</a>`).join('')+'<a href="https://evil.example/blog/1">external</a>'};});await adapter.discover({checkedAt:provenance.checkedAt,deadline:Date.now()+1000});assert.ok(requested.length<=RADAR_LIMITS.indexPages+RADAR_LIMITS.articlePages);assert.ok(requested.every(url=>new URL(url).hostname.endsWith('frontrun.vc')));});
test('X search bounded, unrelated users rejected, results unverified',async()=>{let calls=0;const adapter=new FrontRunXSource({search:async(_q,options)=>{calls++;assert.equal(options.maxResults,3);return [{url:'https://twitter.com/frontrunvc/status/123',title:'early',snippet:'EARLY: @Project - 6 followers'},{url:'https://x.com/other/status/123',title:'other',snippet:'EARLY: @Fake - 1 followers'}];}});const r=await adapter.discover({checkedAt:provenance.checkedAt,deadline:Date.now()+1000});assert.equal(calls,2);assert.equal(r.diagnostics.rejected,2);assert.equal(r.events[0].evidence[0].verification,'UNVERIFIED');});
test('cache GET inert, explicit refresh coalesced and cooldown enforced',async()=>{let calls=0;const service=createRadarService({adapters:[{id:'test',discover:async()=>{calls++;return {events:parse(fixtures.early),diagnostics:{status:'AVAILABLE',issues:[]}};}}]});assert.equal(service.get().refreshedAt,null);assert.equal(calls,0);await Promise.all([service.refresh(),service.refresh()]);await service.refresh();assert.equal(calls,1);const snapshot=service.get();snapshot.discoveries.length=0;assert.equal(service.get().discoveries.length,1);});
test('both source failure directions isolated and sanitized',async()=>{for(const fail of ['frontrunWebsite','frontrunX']){const service=createRadarService({adapters:['frontrunWebsite','frontrunX'].map(id=>({id,discover:async()=>{if(id===fail)throw Error('secret-key private-upstream-body');return {events:parse(fixtures.early),diagnostics:{status:'AVAILABLE',issues:[]}};}}))});const r=await service.refresh();assert.equal(r.discoveries.length,1);assert.equal(r.sources[fail].status,'UNAVAILABLE');assert.ok(!JSON.stringify(r).includes('secret'));}});
test('adapter failures sanitized and absent X configuration diagnosed',async()=>{const x=await new FrontRunXSource(null).discover({checkedAt:provenance.checkedAt,deadline:Date.now()+1000});assert.equal(x.diagnostics.status,'NOT_CONFIGURED');const w=await new FrontRunWebsiteSource(async()=>{throw Error('secret');}).discover({checkedAt:provenance.checkedAt,deadline:Date.now()+1000});assert.equal(w.diagnostics.status,'UNAVAILABLE');assert.ok(!JSON.stringify(w).includes('secret'));});
test('noscript index preserved and www retained for retrieval',async()=>{const calls=[];const adapter=new FrontRunWebsiteSource(async url=>{calls.push(url);return {url,html:calls.length===1?'<noscript><a href="/blog/receipt">receipt</a></noscript>':'<p>EARLY: @Project - 6 followers</p>'};});const r=await adapter.discover({checkedAt:provenance.checkedAt,deadline:Date.now()+1000});assert.equal(calls[1],'https://www.frontrun.vc/blog/receipt');assert.equal(r.events.length,1);});
test('receipt funding amount with unnamed round stays raw',()=>{const [d]=parse('@orthogonal_sh flagged 184 days before a $4.3M round led by Pantera');assert.equal(d.fundingAmount,'$4.3M');assert.equal(d.fundingRound,null);assert.deepEqual(d.investors,['Pantera']);assert.equal(d.frontRunLeadTimeDays,184);});
test('expired deadline makes no requests',async()=>{const fail=()=>{throw Error('must not call');};const context={checkedAt:provenance.checkedAt,deadline:Date.now()-1};const w=await new FrontRunWebsiteSource(fail).discover(context);const x=await new FrontRunXSource({search:fail}).discover(context);assert.equal(w.diagnostics.pagesRequested,0);assert.equal(x.diagnostics.queriesAttempted,0);});
test('refresh retains previous successful evidence for a failing generic adapter',async()=>{let failure=false;let calls=0;const service=createRadarService({cooldown:0,adapters:[{id:'custom',discover:async()=>{calls++;if(failure)throw Error('secret');return {events:parseDiscoveryText(fixtures.early,{...provenance,sourceId:'custom'}),diagnostics:{status:'AVAILABLE',issues:[]}};}}]});await service.refresh();failure=true;const r=await service.refresh();assert.equal(calls,2);assert.equal(r.discoveries.length,1);assert.equal(r.sources.custom.status,'UNAVAILABLE');assert.equal(r.counts.rawEvents,0);});
test('API GET never refreshes; explicit POST rejects cross-origin and sanitizes failure',async()=>{const {readFileSync}=await import('node:fs');const {createRequire}=await import('node:module');const ts=createRequire(import.meta.url)('typescript');let calls=0;globalThis.__radarApiMock={get:()=>({discoveries:[]}),refresh:async()=>{calls++;throw Error('secret upstream');}};const load=async path=>{let source=readFileSync(new URL(path,import.meta.url),'utf8').replace(/import \{ NextResponse \} from "next\/server";/,'const NextResponse = Response;').replace(/import \{ radarService \} from "@\/lib\/radar\/discovery.mjs";/,'const radarService = globalThis.__radarApiMock;');source=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2020}}).outputText;return import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);};const get=await load('../app/api/radar/route.ts');assert.equal((await get.GET()).status,200);assert.equal(calls,0);const post=await load('../app/api/radar/refresh/route.ts');const rejected=await post.POST(new Request('https://captain.example/api/radar/refresh',{method:'POST',headers:{origin:'https://evil.example'}}));assert.equal(rejected.status,403);assert.equal(calls,0);const failed=await post.POST(new Request('https://captain.example/api/radar/refresh',{method:'POST'}));assert.equal(calls,1);assert.equal(failed.status,503);assert.ok(!(await failed.text()).includes('secret'));delete globalThis.__radarApiMock;});
test('successful refresh preserves earlier events and first retrieval time',async()=>{let n=0;const service=createRadarService({cooldown:0,now:()=>new Date(`2026-10-0${n+1}T12:00:00Z`),adapters:[{id:'custom',discover:async({checkedAt})=>{n++;return {events:parseDiscoveryText(`EARLY: @Project - ${n} followers`,{...provenance,checkedAt,sourceId:'custom'}),diagnostics:{status:'AVAILABLE',issues:[]}};}}]});await service.refresh();const d=(await service.refresh()).discoveries[0];assert.equal(d.evidence.length,2);assert.equal(d.discoveredAt,'2026-10-01T12:00:00.000Z');});
test('identity bridge retains data from both previously separate groups',()=>{const events=parse('EARLY: @Project - 6 followers\nCompany raised $41M seed led by Accel https://company.example/\nEARLY: @Project - 10 followers https://company.example/');const [d]=normalizeDiscoveries(events);assert.equal(normalizeDiscoveries(events).length,1);assert.equal(d.evidence.length,3);assert.equal(d.fundingAmount,'$41M');assert.deepEqual(d.investors,['Accel']);});
test('article publication date stays separate from flag date and scripts ignored',async()=>{const source=new FrontRunWebsiteSource(async url=>({url,html:'<title>Launch</title><time datetime="2026-09-15"></time><script>EARLY: @Fake - 6 followers</script><p>EARLY: @Real - 6 followers flagged 2026-08-10</p>'}));const r=await source.discover({checkedAt:provenance.checkedAt,deadline:Date.now()+1000});assert.equal(r.events.length,1);assert.equal(r.events[0].evidence[0].sourcePublishedAt,'2026-09-15');assert.equal(r.events[0].frontRunFlaggedAt,'2026-08-10');});
test('blog index prioritized before editorial articles exhaust budget',async()=>{const calls=[];const source=new FrontRunWebsiteSource(async url=>{calls.push(url);return {url,html:new URL(url).pathname==='/'?'<a href="/blog">Blog</a>'+Array.from({length:12},(_,i)=>`<a href="/blog/guide-${i}">guide</a>`).join(''):new URL(url).pathname==='/blog'?'<a href="/blog/fundraise-receipt">Receipt</a>':'<p>EARLY: @Project - 6 followers</p>'};});await source.discover({checkedAt:provenance.checkedAt,deadline:Date.now()+1000});assert.ok(calls.includes('https://www.frontrun.vc/blog/fundraise-receipt'));assert.ok(calls.length<=RADAR_LIMITS.indexPages+RADAR_LIMITS.articlePages);});
test('decimal funding amounts and explicit founders remain intact',()=>{const [d]=parse('Company raised $4.3M seed led by Accel');assert.equal(d.fundingAmount,'$4.3M');assert.equal(d.fundingRound,'seed');const [early]=parse('EARLY: @Project - 6 followers founder: Alice (@Alice) flagged 2026-08-10');assert.deepEqual(early.founderNames,['Alice']);assert.deepEqual(early.founderHandles,['alice']);assert.equal(parse('EARLY: @Project - $41M seed led by Accel')[0].investors[0],'Accel');});

test('relative public links resolve and navigation, legal and static links are excluded',async()=>{
  const {frontRunLink}=await import('../lib/radar/discovery.mjs');
  assert.equal(frontRunLink('fundraise_receipts-2026-10-01/','https://www.frontrun.vc/blog/'),'https://www.frontrun.vc/blog/fundraise_receipts-2026-10-01');
  for(const path of ['/privacy','/terms','/docs','/assets/early.js','/blog/photo.png','/login','https://other.example/blog/receipt'])assert.equal(frontRunLink(path,'https://www.frontrun.vc/'),null);
});
test('duplicate index URLs and fragment links consume one request',async()=>{
  const calls=[];const source=new FrontRunWebsiteSource(async url=>{calls.push(url);return {url,html:calls.length===1?'<noscript><a href="/blog/receipt/">receipt</a><a href="/blog/receipt#entry">same</a></noscript>':'<p>EARLY: @Project - 12 followers (AI)</p>'};});
  const r=await source.discover({checkedAt:provenance.checkedAt,deadline:Date.now()+1000});assert.equal(calls.length,2);assert.equal(r.events.length,1);
});
test('live-style numbered receipt isolates project handles and lead claims',()=>{
  const items=parse("Today's fundraises. @frontrunvc flagged 2 startups. 1. @PhotonHQ - 97 days ago. $4.5M seed led by @gradientvc 2. @HalluminateAI - 49 days ago. $30M Series A led by @oakhcft");
  assert.deepEqual(items.map(e=>e.projectHandle),['photonhq','halluminateai']);assert.equal(items[0].frontRunLeadTimeDays,97);assert.equal(items[0].frontRunFlaggedAt,null);assert.equal(items[0].fundingAmount,'$4.5M');
});
test('live receipt sections bind full explicit date and originating status',async()=>{
  const {parseFrontRunPage}=await import('../lib/radar/discovery.mjs');
  const html='<h2>Photon: $4.5M seed, flagged 97 days before the announcement</h2><p><a href="https://x.com/PhotonHQ">Photon</a> brings AI agents. the round is a $4.5M seed led by Gradient.</p><p>flagged june 26 2026, announced october 1 2026. 97 days.</p><p><a href="https://x.com/frontrunvc/status/123">view the post on X →</a></p>';
  const [d]=parseFrontRunPage(html,provenance.sourceUrl,provenance).events;
  assert.equal(d.projectHandle,'photonhq');assert.equal(d.frontRunFlaggedAt,'2026-06-26');assert.equal(d.frontRunLeadTimeDays,97);assert.deepEqual(d.investors,['Gradient']);assert.equal(d.projectWebsite,null);assert.equal(d.evidence[0].originatingPostUrl,'https://x.com/frontrunvc/status/123');
});
test('lead-time and incomplete dates never manufacture a flag date',()=>{
  for(const text of ['EARLY: @Project - 123 days early','@Project - flagged feb 23 at 13 followers. $3M pre-seed 123 days later']){const [d]=parse(text);assert.equal(d.frontRunFlaggedAt,null);assert.equal(d.frontRunLeadTimeDays,123);}
});
test('aggregate X snippets retain exact status metadata without inventing project identities',async()=>{
  const adapter=new FrontRunXSource({search:async()=>[{url:'https://twitter.com/frontrunvc/status/123',title:'frontrun on X',snippet:'EARLY: 5 companies across AI and FinTech.',publishedAt:'2026-10-01'}]});
  const r=await adapter.discover({checkedAt:provenance.checkedAt,deadline:Date.now()+1000});assert.equal(r.events.length,0);assert.equal(r.diagnostics.statusDiscoveries[0].sourceUrl,'https://x.com/frontrunvc/status/123');assert.equal(r.diagnostics.statusDiscoveries[0].evidenceKind,'DISCOVERY_ONLY');assert.equal(r.diagnostics.statusDiscoveries[0].verification,'UNVERIFIED');
});
test('zero X results is a successful empty search',async()=>{
  const r=await new FrontRunXSource({search:async()=>[]}).discover({checkedAt:provenance.checkedAt,deadline:Date.now()+1000});assert.equal(r.diagnostics.queriesSuccessful,2);assert.equal(r.diagnostics.status,'AVAILABLE');assert.equal(r.events.length,0);
});
test('X query budget allows measured provider latency and exact ownership only',async()=>{
  const adapter=new FrontRunXSource({search:async(query,options)=>{assert.match(query,/site:x.com\/frontrunvc\/status/);assert.ok(options.timeout>4000);return [{url:'https://x.com/other/status/1',title:'other',snippet:'EARLY: @Fake - 6 followers'},{url:'https://x.com/frontrunvc/status/123/quotes',title:'quotes',snippet:'EARLY: @Fake - 6 followers'}];}});
  const r=await adapter.discover({checkedAt:provenance.checkedAt,deadline:Date.now()+30000});assert.equal(r.events.length,0);assert.equal(r.diagnostics.rejected,4);
});
test('linked-page failure preserves homepage events and exposes sanitized category',async()=>{
  const source=new FrontRunWebsiteSource(async url=>{if(new URL(url).pathname!=='/')throw Error('Research timed out');return {url,html:'<p>EARLY: @Project - 6 followers</p><a href="/blog/receipt">receipt</a>'};});const r=await source.discover({checkedAt:provenance.checkedAt,deadline:Date.now()+1000});assert.equal(r.events.length,1);assert.equal(r.diagnostics.status,'PARTIAL');assert.match(r.diagnostics.issues[0],/TIMEOUT/);
});
test('unrelated explicit external links cannot become an official project website',()=>{
  const [d]=parseDiscoveryText('EARLY: @Project - 6 followers Read investor profile',provenance,[{label:'investor profile',url:'https://investor.example/'}]);assert.equal(d.projectWebsite,null);
});
test('live X quote pronouns do not become projects; explicit FrontRun title supplies identity',()=>{
  assert.deepEqual(parse('We raised a $35M Series A led by @oakhcft'),[]);
  const [d]=parse('frontrunvc flagged @rtp on April 2nd. 160 days later: ... We raised a $35M Series A led by @oakhcft');
  assert.equal(d.projectHandle,'rtp');assert.equal(d.frontRunFlaggedAt,null);assert.equal(d.frontRunLeadTimeDays,160);assert.equal(d.fundingAmount,'$35M');
  assert.deepEqual(parse('frontrunvc flagged Instinct founder @noahrshinn 53 days ...'),[]);
});
test('homepage has bounded bootstrap allowance; articles retain four-second budget',async()=>{
  const source=new FrontRunWebsiteSource(async(url,{timeout})=>{assert.ok(timeout<=12000);if(new URL(url).pathname==='/')assert.ok(timeout>4000);else assert.ok(timeout<=4000);return {url,html:new URL(url).pathname==='/'?'<a href="/blog/receipt">receipt</a>':'<p>EARLY: @Project - 6 followers</p>'};});await source.discover({checkedAt:provenance.checkedAt,deadline:Date.now()+30000});
});
test('status metadata preserves first retrieval and survives subsequent X failure',async()=>{
  let fail=false;const adapter=new FrontRunXSource({search:async()=>{if(fail)throw Error('secret upstream');return [{url:'https://x.com/frontrunvc/status/123',title:'frontrun',snippet:'EARLY: 5 companies across AI.'}];}});
  const service=createRadarService({adapters:[adapter],cooldown:0});const first=await service.refresh();fail=true;const second=await service.refresh();assert.equal(second.sources.frontrunX.status,'UNAVAILABLE');assert.equal(second.sources.frontrunX.statusDiscoveries.length,1);assert.equal(second.sources.frontrunX.statusDiscoveries[0].checkedAt,first.sources.frontrunX.statusDiscoveries[0].checkedAt);assert.ok(!JSON.stringify(second).includes('secret'));
});
